let save = document.getElementsByClassName('btn btn-primary btn-sm');
let env_ws = document.getElementById('env_ws');
let env_ws_json = JSON.parse(env_ws.textContent);
// env_ws_json.DOCK.BACK_TO_URL = 'https://food2.vsd.app?checkModules=false';
// env_ws_json.PAYMENT.MULTIPLE_CARDS.ENABLED = 'false';
env_ws_json.PARTNER.BRAND_CARD_LIST['10315'] = '23';
env_ws_json.PARTNER.BRAND_CARD_LIST['00057'] = '15';
env_ws_json.PARTNER.BRAND_CARD_LIST['00408'] = '15';
env_ws_json.PARTNER.BRAND_CARD_LIST['00421'] = '15';
env_ws_json.PARTNER.BRAND_CARD_LIST['10269'] = '8';
env_ws_json.PARTNER.BRAND_CARD_LIST['10282'] = '12';
env_ws_json.PARTNER.BRAND_CARD_LIST['10237'] = '12';
env_ws_json.PARTNER.BRAND_CARD_LIST['10238'] = '12';
env_ws.textContent = JSON.stringify(env_ws_json, null, 4);
save[0].click();
